### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by bendrucker** [stefansundin/terraform-provider-ssh#11]
I noticed the note in the readme:

> This provider does not support Terraform v0.12 yet. There were some changes made that makes the upgrade non-trivial.

Could you share what parts of the upgrade you believe will be nontrivial? This provider would help us out a lot at @takescoop, happy to work on the upgrade and support future maintenance!

**Comment by stefansundin** [comment]
It appears that Terraform is forcing all plugins to close in v0.12, so it doesn't seem possible to keep the SSH connection open by just running them in go routines the way it is currently done.

My current thinking is that I'll try to just fork off a new process that can be sent configuration somehow, and then that new process will stay running as long as the main terraform process is running. When the terraform process terminates, the forked process can then exit as well.

I was planning to post in the Terraform mailing list to see if the people at HashiCorp have any better suggestions too, but I haven't had the time to do so yet.

**Comment by bendrucker** [comment]
Much appreciated, that makes a lot of sense. HashiCorp has a new forum for technical discussion:

https://discuss.hashicorp.com/c/terraform-core

I'd be more than happy to take up this issue and put a write up on the forum soliciting comments, sound good?

**Comment by stefansundin** [comment]
Ah, nice. Sure, feel free to create a new topic. I just created a user over there so you can @-mention me in the topic if you'd like.

**Comment by bendrucker** [comment]
Sorry for the long delay/silence on this one. I summarized the state of this provider and the 0.12 issues in a post on the HashiCorp forum:

https://discuss.hashicorp.com/t/provider-plugins-that-live-for-the-duration-of-a-terraform-run/2262?u=bendrucker
