### ISSUE TITLE
If private_key is not specified, try to use of SSH-Agent for authentication

### ISSUE THREAD

**Issue by rojaro** [stefansundin/terraform-provider-ssh#4]
http://blog.ralch.com/tutorial/golang-ssh-connection/

**Comment by rojaro** [comment]
http://blog.ralch.com/tutorial/golang-ssh-connection/

**Comment by stefansundin** [comment]
That's a good idea. I am planning to update this when Terraform 0.12 is released, so hopefully at that time.

**Comment by stefansundin** [comment]
Fixed by https://github.com/stefansundin/terraform-provider-ssh/pull/6.
