### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by nexusix** [stefansundin/terraform-provider-ssh#8]
Hey. How about version bump, for example to 0.1. At the moment, terraform shows provider version 0.0, and this a bit confusing.

**Comment by stefansundin** [comment]
I want to do it, but I just haven't had time yet. For now you have to compile it yourself.

**Comment by nexusix** [comment]
I can create pull request ;)

**Comment by stefansundin** [comment]
Released v0.0.3. https://github.com/stefansundin/terraform-provider-ssh/releases/tag/v0.0.3
